spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: 123
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console.enabled: true
    liquibase:
        drop-first: false
        changeLog: classpath:db/changelog/db.changelog-master.yaml



